
sort_order = [
    "tmuxinator", # show first
    "tmux",
    "config",
    "zoxide", # show last
]


[[session]]
name = "home üè°"
path = "~"

[[session]]
name = "work üíº"
path = "~/work"
startup_command = "yazi"

[[session]]
name = "personal üçï"
path = "~/personal"
startup_command = "yazi"

[[session]]
name = "neovim config"
path = "~/.config/nvim"

[[session]]
name = "sesh config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --language=toml --style=snip --color=always ~/.config/sesh/sesh.toml"

[[session]]
name = "zsh config"
path = "~/.config/zsh"
startup_command = "nvim .zshrc"

[[session]]
name = "yazi config"
path = "~/.config/yazi"
startup_command = "nvim yazi.toml"
preview_command = "bat --color=always ~/.config/yazi/yazi.toml"

[[session]]
name = "wezterm config"
path = "~/.config/wezterm"
startup_command = "nvim wezterm.lua"
preview_command = "bat --color=always ~/.config/wezterm/wezterm.lua"


[[session]]
name = "tsumiki config"
path = "~/.config/tsumiki"
startup_command = "sh init.sh -start"


[[session]]
name = "bin üíª"
path = "~/.config/bin"
startup_command = "nvim ."

[[session]]
name = "tmux "
path = "~/.config/tmux"
startup_command = "nvim tmux.conf.local"
preview_command = "bat --color=always ~/.config/tmux/tmux.conf.local"

[[session]]
name = "dotfiles"
path = ".local/share/chezmoi"
startup_command = "lazygit"

[[session]]
name = "downloads üì•"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "lazy plugins"
path = "~/.local/share/nvim/lazy"
startup_command = "sesh connect (ls | fzf --no-border --preview 'glow -s auto {}/README.md') && exit"
