
[[session]]
name = "home ğŸ¡"
path = "~"

[[session]]
name = "work ğŸ’¼"
path = "~/work"
startup_command = "yazi"

[[session]]
name = "personal ğŸ•"
path = "~/personal"
startup_command = "yazi"

[[session]]
name = "neovim config"
path = "~/.config/nvim"

[[session]]
name = "zsh config"
path = "~/.config/zsh"
startup_command = "nvim .zshrc"

[[session]]
name = "yazi config"
path = "~/.config/yazi"
startup_command = "nvim yazi.toml"

[[session]]
name = "wezterm config"
path = "~/.config/wezterm"
startup_command = "nvim wezterm.lua"


[[session]]
name = "tsumiki config"
path = "~/.config/tsumiki"
startup_command = "sh init.sh -start"

[[session]]
name = "sesh config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "bin ğŸ’»"
path = "~/.config/bin"
startup_command = "nvim ."

[[session]]
name = "tmux "
path = "~/.config/tmux"
startup_command = "nvim tmux.conf.local"

[[session]]
name = "dotfiles"
path = ".local/share/chezmoi"
startup_command = "lazygit"

[[session]]
name = "downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "lazy plugins"
path = "~/.local/share/nvim/lazy"
startup_command = "sesh connect (ls | fzf --no-border --preview 'glow -s auto {}/README.md') && exit"
