[default_session]
startup_command = "nvim +GoToFile"

[[session]]
name = "Home üè°"
path = "~"
startup_command = "yazi"

[[session]]
name = "Code üíª"
path = "~/personal"
startup_command = "yazi"


[[session]]
name = "hammerspoon config"
path = "~/c/dotfiles/.hammerspoon"

[[session]]
name = "neovim config"
path = "~/.config/nvim"

[[session]]
name = "zsh config"
path = "~/.config/zsh"
startup_command = "nvim .zshrc"

[[session]]
name = "yazi config"
path = "~/.config/yazi"
startup_command = "nvim yazi.toml"

[[session]]
name = "wezterm config"
path = "~/.config/wezterm"
startup_command = "nvim wezterm.lua"


[[session]]
name = "sesh config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "bin"
path = "~/.config/bin"
startup_command = "nvim ."

[[session]]
name = "tmux ÓØà"
path = "~/config/tmux"
startup_command = "nvim tmux.local.conf"

[[session]]
name = "dotfiles"
path = ".local/share/chezmoi"
startup_command = "lazygit"

[[session]]
name = "Downloads üì•"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "lazy plugins"
path = "~/.local/share/nvim/lazy"
startup_command = "sesh connect (ls | fzf --no-border --preview 'glow -s auto {}/README.md') && exit"
