"$schema" = "https://raw.githubusercontent.com/HyDE-Project/HyDE/refs/heads/master/Configs/.local/share/hyde/schema/config.toml.json"

[volume]
# volumecontrol.sh configuration
notify = false    # Useful for systems that have their own OSD
steps = 5         # Number of steps to increase/decrease volume
boost = true      # Enable volume boost
boost_limit = 150 # Volume boost limit // Don't kill your ears/speakers

[brightness]
# brightnesscontrol.sh configuration
notify = false # Useful for systems that have their own OSD

[battery.notify.threshold]
full = 100
critical = 10
low = 20
unplug = 80

[wallpaper]
custom_paths = [
    "$HOME/Pictures/Wallpapers",
] # List of paths to search for wallpapers


[hyprland]
browser = "vivaldi"  # Browser.
editor = "code-insiders" # Editor.
terminal = "wezterm"     # Terminal.
quickapps = "wezterm"    # Quick apps.

[hyprland.start]
bar = ''
apptray_bluetooth = ''
